<h2>Modifier le produit : <?= htmlspecialchars($meals["nameMeal"]) ?></h2>
<p class="right"><a href="index.php?action=displayMeals">Retour à la liste des produits</a></p>

<form action="index.php?action=updateMeal&meal_id=<?= $meal_ID ?>" method='post' enctype="multipart/form-data">
    
    <fieldset>
        <legend>Caractéristiques</legend>
        <ul>
            <li>
                <label for="name">Nom :</label>
                <input type="text" name="name" id="name" value="<?= htmlspecialchars($meals["nameMeal"]) ?>">
            </li>
            <li>
                <label for="description">Description :</label>
                <textarea name="description" id="description"><?= htmlspecialchars($meals["description"]) ?></textarea>
            </li>
            <li>
                <label for="image">Image :</label>
                <ul>
                    <li>
                        <img class="imageList" src="public/images/meals/<?= htmlspecialchars($meals["image"]) ?>" alt="<?= htmlspecialchars($meals["description"]) ?>"/>
                    </li>
                    <li>
                        <label class="check"><input type="checkbox" id="check" name="oldImage" checked>Conserver mon ancien Avatar</label>
                    </li>
                    <li>
                        <input type="file" name="image">
                    </li>
                </ul>
            </li>
        </ul>
    </fieldset>
    <fieldset>
        <legend>Approvisionnement</legend>
        <label for="price">Prix de vente :</label>
        <input type="text" name="price" id="price" value="<?= htmlspecialchars($meals["price"]) ?>">
    </fieldset>
    
    <input type="submit" id="submit" name="updateMeal" value="Modifier">
    <input type="reset" value="Annuler">
    
</form>

<script type="module" src="public/js/meal/app.js"></script>