<ul class="link-list">
    <li>
        <a class="button button-primary" href="index.php?action=displayMeals">Afficher les produits</a>
    </li>
    <li>
        <a class="button button-primary" href="index.php?action=displayBooking">Afficher la liste des réservations</a>
    </li>
    <li>
        <a class="button button-primary" href="index.php?action=displayOrders">Afficher la liste des commandes</a>
    </li>
</ul>